### ISSUE TITLE
Week1-Assignment

### ISSUE THREAD

**Issue by Larousse24** [Larousse24/Larousse24-ag-problems-semester#1]
Email Zack the link to this repo
Upload a data file

**Comment by Larousse24** [comment]
@brymz, which data file should I use?

**Comment by brymz** [comment]
Part of this assignment is for you to choose. The options in my mind that would work to accompany your project are:
- https://github.com/TREC-Agroecology/agroecosystems/blob/master/data/Dry_Biomass_Raw_2019_Summer_TREC.csv
- https://github.com/TREC-Agroecology/agroecosystems/blob/master/data/soil-BD-092018.csv
- Or a few months from the weather station data that includes temp, humidity, rain, and soil moisture

**Comment by Larousse24** [comment]
@brymz, I am done for the week.
