### ISSUE TITLE
Assignment 4

### ISSUE THREAD

**Issue by Larousse24** [Larousse24/Larousse24-ag-problems-semester#4]
@brymz, I am actually working with two different dataset so far, should I follow all the steps for both of them?

**Comment by brymz** [comment]
Hi Larousse, I think working with two datasets make sense. One to learn the lesson. The second to test your learning. I was looking back at Issue #3 where you describe your analysis for the class. I will be checking your analysis matches that description, so feel free to keep it updated with your current approach.

**Comment by Larousse24** [comment]
@brymz  I got it. I don't know  If you had a chance to look to at the description of my analysis and the two datasets that I uploaded. I think I need them both for the analysis. Otherwise, I will have to look for a better one or slightly change my analysis description to work them. I might have to upload a new one and repeat all of the processes.

**Comment by Larousse24** [comment]
@brymz, I am done for this week, but I am ready to go back in case there is something to change before moving forward.
